### ISSUE TITLE
`parse': 765: unexpected token at '' (JSON::ParserError)

### ISSUE THREAD

**Issue by kenchon** [syamoji/getInstagram#1]
ruby初心者で申し訳ないのですが、
冒頭の取得データ数などのパラメータを適当に変更して実行したところ、下記エラーが出ました：
```
dress のデータを 10 件取得します
Traceback (most recent call last):
	2: from getImageWithTag.rb:205:in `<main>'
	1: from /usr/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/usr/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '' (JSON::ParserError)
```
こちら対応可能でしょうか。よろしくお願いいたします。

**Comment by syamoji** [comment]
ちょっと見てみます。

**Comment by syamoji** [comment]
InstagramのWebページ構造が変更になっていたことが原因でした。
ひとまずエラーを出さずに取得するように修正しましたが、2ページ目以降の取得方法がまだわからないので、1ページ分だけ取得するようになっています。
およそ73投稿分取得できるようです。
再度お試しください。
よろしくお願い致します。
